### ISSUE TITLE
AttributeError: 'FlexiVisionTransformer' object has no attribute '_backward_hooks'

### ISSUE THREAD

**Issue by striver123456** [bwconrad/flexivit#1]
Traceback (most recent call last):
  File "xx.py", line 7, in <module>
    preds = net(img)
  File "/home/dell/anaconda3/envs/fvit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1192, in _call_impl
    if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
  File "/home/dell/anaconda3/envs/fvit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1270, in __getattr__
    type(self).__name__, name))
AttributeError: 'FlexiVisionTransformer' object has no attribute '_backward_hooks'

**Comment by striver123456** [comment]
how to solve it? Thanks!

**Comment by striver123456** [comment]
Thank you for your reply。
My initial mistake was as follows：
Traceback (most recent call last):
  File "xx.py", line 4, in <module>
    net = flexivit_tiny()
  File "/media/dell/A0BA0D9FBA0D72D8/fvit/flexivit_pytorch/flexivit.py", line 168, in flexivit_tiny
    return FlexiVisionTransformer(embed_dim=192, depth=12, num_heads=3, **kwargs)
  File "/media/dell/A0BA0D9FBA0D72D8/fvit/flexivit_pytorch/flexivit.py", line 125, in __init__
    block_fn,  # type:ignore
TypeError: __init__() takes from 1 to 24 positional arguments but 25 were given
There may be an error in the parameters inside  ---- super().__init__()  in flexivit.py

**Comment by bwconrad** [comment]
What version of the `timm` library are you using? It should be at least `0.8.15.dev0`. Having an older version will cause the positional arguments error.
